### PR TITLE
Replace deprecated action node12 with node16

### PR DESCRIPTION
**Pull request by award28**
While testing out this action I received a deprecation warning to upgrade to `node16`. This PR performs that upgrade.

### CODE REVIEW

**Comment by nsandary** [comment]
We're also receiving the warning. Is this package still maintained?

**Comment by award28** [comment]
I don't think so. I've forked the repo and upgraded the node version; feel free to use my fork

**Comment by miparnisari** [comment]
I've also forked this repo and updated the node version + added a few fields that i want in my pagerduty alert. See https://github.com/miparnisari/action-pagerduty-alert

**Comment by JohJonker** [comment]
Fixed in the latest version. Thanks for everyone's contributions!

**Pull request closed without merging**
