### PR TITLE
Support for dedupe key

### PR DESCRIPTION
**Pull request by szunami**
Addresses #1 , cc @JohJonker

### CODE REVIEW

**Comment by szunami** [comment]
@JohJonker I think this PR is ready for another look.

**Comment by szunami** [comment]
@JohJonker any chance you have the time to review this? :)

**Comment by JohJonker** [comment]
Hi @szunami, apologies for the delay. Thanks for making the changes! This looks good. I'm just going to rename the `dedup_key` input parameter to `dedup-key` after approving the PR if that's fine by you, for consistency with the existing parameter.

**Comment by szunami** [comment]
Sounds good to me; when you feel comfortable with this, would you mind cutting a release?

**Comment by JohJonker** [comment]
Sure! I'll have it ready in the next 15-30 mins.

**Pull request merged**
